CLUSTERS = [
    {
        "display_name": "Account Login Cluster",
        "delegate_link_name": "Account Login",
        "delegate_impl_link_name": "Account Login Delegate",
        "delegate_link_url": "https://github.com/espressif/connectedhomeip/blob/d144bbb/src/app/clusters/account-login-server/account-login-delegate.h",
        "delegate_impl_link_url": "https://github.com/espressif/connectedhomeip/blob/d144bbb/examples/tv-app/android/include/account-login/AccountLoginManager.h",
    },
    {
        "display_name": "Actions Cluster",
        "delegate_link_name": "Actions",
        "delegate_impl_link_name": "Actions Delegate",
        "delegate_link_url": "https://github.com/espressif/connectedhomeip/blob/d144bbb/src/app/clusters/actions-server/actions-server.h",
        "delegate_impl_link_url": "https://github.com/espressif/connectedhomeip/blob/d144bbb/examples/all-clusters-app/all-clusters-common/include/bridged-actions-stub.h",
    },
    {
        "display_name": "Application Basic Cluster",
        "delegate_link_name": "Application Basic",
        "delegate_impl_link_name": "Application Basic Delegate",
        "delegate_link_url": "https://github.com/espressif/connectedhomeip/blob/d144bbb/src/app/clusters/application-basic-server/application-basic-delegate.h",
        "delegate_impl_link_url": "https://github.com/espressif/connectedhomeip/blob/d144bbb/examples/tv-app/tv-common/clusters/application-basic/ApplicationBasicManager.h",
    },
    {
        "display_name": "Application Launcher Cluster",
        "delegate_link_name": "Application Launcher",
        "delegate_impl_link_name": "Application Launcher Delegate",
        "delegate_link_url": "https://github.com/espressif/connectedhomeip/blob/d144bbb/src/app/clusters/application-launcher-server/application-launcher-delegate.h",
        "delegate_impl_link_url": "https://github.com/espressif/connectedhomeip/blob/d144bbb/examples/tv-app/tv-common/clusters/application-launcher/ApplicationLauncherManager.h",
    },
    {
        "display_name": "Audio Output Cluster",
        "delegate_link_name": "Audio Output",
        "delegate_impl_link_name": "Audio Output Delegate",
        "delegate_link_url": "https://github.com/espressif/connectedhomeip/blob/d144bbb/src/app/clusters/audio-output-server/audio-output-delegate.h",
        "delegate_impl_link_url": "https://github.com/espressif/connectedhomeip/blob/d144bbb/examples/tv-app/tv-common/clusters/audio-output/AudioOutputManager.h",
    },
    {
        "display_name": "Boolean State Configuration Cluster",
        "delegate_link_name": "Boolean State Configuration",
        "delegate_impl_link_name": "Boolean State Configuration Delegate",
        "delegate_link_url": "https://github.com/espressif/connectedhomeip/blob/d144bbb/src/app/clusters/boolean-state-configuration-server/boolean-state-configuration-delegate.h",
        "delegate_impl_link_url": "https://github.com/espressif/connectedhomeip/blob/d144bbb/examples/all-clusters-app/all-clusters-common/src/boolcfg-stub.cpp",
    },
    {
        "display_name": "Camera AV Settings User Level Management Cluster",
        "delegate_link_name": "Camera AV Settings User Level Management",
        "delegate_impl_link_name": "Camera AV Settings User Level Management Delegate",
        "delegate_link_url": "https://github.com/espressif/connectedhomeip/blob/d144bbb/src/app/clusters/camera-av-settings-user-level-management-server/camera-av-settings-user-level-management-server.h",
        "delegate_impl_link_url": "https://github.com/espressif/connectedhomeip/blob/d144bbb/examples/all-clusters-app/all-clusters-common/include/camera-av-settings-user-level-management-instance.h",
    },
    {
        "display_name": "Channel Cluster",
        "delegate_link_name": "Channel",
        "delegate_impl_link_name": "Channel Delegate",
        "delegate_link_url": "https://github.com/espressif/connectedhomeip/blob/d144bbb/src/app/clusters/channel-server/channel-delegate.h",
        "delegate_impl_link_url": "https://github.com/espressif/connectedhomeip/blob/d144bbb/examples/tv-app/tv-common/clusters/channel/ChannelManager.h",
    },
    {
        "display_name": "Closure Control Cluster",
        "delegate_link_name": "Closure Control",
        "delegate_impl_link_name": "Closure Control Delegate",
        "delegate_link_url": "https://github.com/espressif/connectedhomeip/blob/d144bbb/src/app/clusters/closure-control-server/closure-control-cluster-delegate.h",
        "delegate_impl_link_url": "https://github.com/espressif/connectedhomeip/blob/d144bbb/examples/closure-app/closure-common/include/ClosureControlEndpoint.h",
    },
    {
        "display_name": "Closure Dimension Cluster",
        "delegate_link_name": "Closure Dimension",
        "delegate_impl_link_name": "Closure Dimension Delegate",
        "delegate_link_url": "https://github.com/espressif/connectedhomeip/blob/d144bbb/src/app/clusters/closure-dimension-server/closure-dimension-delegate.h",
        "delegate_impl_link_url": "https://github.com/espressif/connectedhomeip/blob/d144bbb/examples/closure-app/closure-common/include/ClosureDimensionEndpoint.h",
    },
    {
        "display_name": "Commodity Price Cluster",
        "delegate_link_name": "Commodity Price",
        "delegate_impl_link_name": "Commodity Price Delegate",
        "delegate_link_url": "https://github.com/espressif/connectedhomeip/blob/faf4d09/src/app/clusters/commodity-price-server/commodity-price-server.h",
        "delegate_impl_link_url": "https://github.com/espressif/connectedhomeip/blob/faf4d09/examples/energy-gateway-app/commodity-price/include/CommodityPriceDelegate.h",
    },
    {
        "display_name": "Commodity Tariff Cluster",
        "delegate_link_name": "Commodity Tariff",
        "delegate_impl_link_name": "Commodity Tariff Delegate",
        "delegate_link_url": "https://github.com/espressif/connectedhomeip/blob/faf4d09/src/app/clusters/commodity-tariff-server/commodity-tariff-server.h",
        "delegate_impl_link_url": "https://github.com/espressif/connectedhomeip/blob/faf4d09/examples/energy-gateway-app/commodity-tariff/include/CommodityTariffInstance.h",
    },
    {
        "display_name": "Commissioner Control Cluster",
        "delegate_link_name": "Commissioner Control",
        "delegate_impl_link_name": "Commissioner Control Delegate",
        "delegate_link_url": "https://github.com/espressif/connectedhomeip/blob/d144bbb/src/app/clusters/commissioner-control-server/commissioner-control-server.h",
        "delegate_impl_link_url": "https://github.com/espressif/connectedhomeip/blob/d144bbb/examples/fabric-bridge-app/linux/include/CommissionerControlDelegate.h",
    },
    {
        "display_name": "Content App Observer Cluster",
        "delegate_link_name": "Content App Observer",
        "delegate_impl_link_name": None,
        "delegate_link_url": "https://github.com/espressif/connectedhomeip/blob/d144bbb/src/app/clusters/content-app-observer/content-app-observer-delegate.h",
        "delegate_impl_link_url": None,
    },
    {
        "display_name": "Content Control Cluster",
        "delegate_link_name": "Content Control",
        "delegate_impl_link_name": None,
        "delegate_link_url": "https://github.com/espressif/connectedhomeip/blob/d144bbb/src/app/clusters/content-control-server/content-control-delegate.h",
        "delegate_impl_link_url": None,
    },
    {
        "display_name": "Content Launcher Cluster",
        "delegate_link_name": "Content Launcher",
        "delegate_impl_link_name": "Content Launcher Delegate",
        "delegate_link_url": "https://github.com/espressif/connectedhomeip/blob/d144bbb/src/app/clusters/content-launch-server/content-launch-delegate.h",
        "delegate_impl_link_url": "https://github.com/espressif/connectedhomeip/blob/d144bbb/examples/tv-app/tv-common/clusters/content-launcher/ContentLauncherManager.h",
    },
    {
        "display_name": "Device Energy Management Cluster",
        "delegate_link_name": "Device Energy Management",
        "delegate_impl_link_name": "Device Energy Management Delegate",
        "delegate_link_url": "https://github.com/espressif/connectedhomeip/blob/d144bbb/src/app/clusters/device-energy-management-server/device-energy-management-server.h",
        "delegate_impl_link_url": "https://github.com/espressif/connectedhomeip/blob/d144bbb/examples/energy-management-app/energy-management-common/device-energy-management/include/DeviceEnergyManagementDelegateImpl.h",
    },
    {
        "display_name": "Dishwasher Alarm Cluster",
        "delegate_link_name": "Dishwasher Alarm",
        "delegate_impl_link_name": "Dishwasher Alarm Delegate",
        "delegate_link_url": "https://github.com/espressif/connectedhomeip/blob/d144bbb/src/app/clusters/dishwasher-alarm-server/dishwasher-alarm-delegate.h",
        "delegate_impl_link_url": "https://github.com/espressif/connectedhomeip/blob/d144bbb/examples/all-clusters-app/all-clusters-common/src/dishwasher-alarm-stub.cpp",
    },
    {
        "display_name": "Door Lock Cluster",
        "delegate_link_name": "Door Lock",
        "delegate_impl_link_name": "Door Lock Delegate",
        "delegate_link_url": "https://github.com/espressif/connectedhomeip/blob/d144bbb/src/app/clusters/door-lock-server/door-lock-delegate.h",
        "delegate_impl_link_url": "https://github.com/espressif/connectedhomeip/blob/d144bbb/examples/lock-app/lock-common/src/LockEndpoint.cpp",
    },
    {
        "display_name": "Electrical Grid Conditions Cluster",
        "delegate_link_name": "Electrical Grid Conditions",
        "delegate_impl_link_name": "Electrical Grid Conditions Delegate",
        "delegate_link_url": "https://github.com/espressif/connectedhomeip/blob/faf4d09/src/app/clusters/electrical-grid-conditions-server/electrical-grid-conditions-server.h",
        "delegate_impl_link_url": "https://github.com/espressif/connectedhomeip/blob/faf4d09/examples/energy-gateway-app/electrical-grid-conditions/include/ElectricalGridConditionsDelegate.h",
    },
    {
        "display_name": "Electrical Power Measurement Cluster",
        "delegate_link_name": "Electrical Power Measurement",
        "delegate_impl_link_name": "Electrical Power Measurement Delegate",
        "delegate_link_url": "https://github.com/espressif/connectedhomeip/blob/d144bbb/src/app/clusters/electrical-power-measurement-server/electrical-power-measurement-server.h",
        "delegate_impl_link_url": "https://github.com/espressif/connectedhomeip/blob/d144bbb/examples/energy-management-app/energy-management-common/energy-reporting/include/ElectricalPowerMeasurementDelegate.h",
    },
    {
        "display_name": "Energy EVSE Cluster",
        "delegate_link_name": "Energy Evse",
        "delegate_impl_link_name": "Energy Evse Delegate",
        "delegate_link_url": "https://github.com/espressif/connectedhomeip/blob/d144bbb/src/app/clusters/energy-evse-server/energy-evse-server.h",
        "delegate_impl_link_url": "https://github.com/espressif/connectedhomeip/blob/d144bbb/examples/energy-management-app/energy-management-common/energy-evse/include/EnergyEvseDelegateImpl.h",
    },
    {
        "display_name": "Energy Preference Cluster",
        "delegate_link_name": "Energy Preference",
        "delegate_impl_link_name": "Energy Preference Delegate",
        "delegate_link_url": "https://github.com/espressif/connectedhomeip/blob/d144bbb/src/app/clusters/energy-preference-server/energy-preference-server.h",
        "delegate_impl_link_url": "https://github.com/espressif/connectedhomeip/blob/d144bbb/examples/all-clusters-app/all-clusters-common/src/energy-preference-delegate.cpp",
    },
    {
        "display_name": "Fan Control Cluster",
        "delegate_link_name": "Fan Control",
        "delegate_impl_link_name": "Fan Control Delegate",
        "delegate_link_url": "https://github.com/espressif/connectedhomeip/blob/d144bbb/src/app/clusters/fan-control-server/fan-control-delegate.h",
        "delegate_impl_link_url": "https://github.com/espressif/connectedhomeip/blob/d144bbb/examples/all-clusters-app/all-clusters-common/src/fan-stub.cpp",
    },
    {
        "display_name": "Keypad Input Cluster",
        "delegate_link_name": "Keypad Input",
        "delegate_impl_link_name": "Keypad Input Delegate",
        "delegate_link_url": "https://github.com/espressif/connectedhomeip/blob/d144bbb/src/app/clusters/keypad-input-server/keypad-input-delegate.h",
        "delegate_impl_link_url": "https://github.com/espressif/connectedhomeip/blob/d144bbb/examples/tv-app/tv-common/clusters/keypad-input/KeypadInputManager.h",
    },
    {
        "display_name": "Laundry Dryer Controls Cluster",
        "delegate_link_name": "Laundry Dryer Controls",
        "delegate_impl_link_name": "Laundry Dryer Controls Delegate",
        "delegate_link_url": "https://github.com/espressif/connectedhomeip/blob/d144bbb/src/app/clusters/laundry-dryer-controls-server/laundry-dryer-controls-delegate.h",
        "delegate_impl_link_url": "https://github.com/espressif/connectedhomeip/blob/d144bbb/examples/all-clusters-app/all-clusters-common/include/laundry-dryer-controls-delegate-impl.h",
    },
    {
        "display_name": "Laundry Washer Controls Cluster",
        "delegate_link_name": "Laundry Washer Controls",
        "delegate_impl_link_name": "Laundry Washer Controls Delegate",
        "delegate_link_url": "https://github.com/espressif/connectedhomeip/blob/d144bbb/src/app/clusters/laundry-washer-controls-server/laundry-washer-controls-delegate.h",
        "delegate_impl_link_url": "https://github.com/espressif/connectedhomeip/blob/d144bbb/examples/all-clusters-app/all-clusters-common/include/laundry-washer-controls-delegate-impl.h",
    },
    {
        "display_name": "Low Power Cluster",
        "delegate_link_name": "Low Power",
        "delegate_impl_link_name": "Low Power Delegate",
        "delegate_link_url": "https://github.com/espressif/connectedhomeip/blob/d144bbb/src/app/clusters/low-power-server/low-power-delegate.h",
        "delegate_impl_link_url": "https://github.com/espressif/connectedhomeip/blob/d144bbb/examples/tv-app/tv-common/clusters/low-power/LowPowerManager.h",
    },
    {
        "display_name": "Media Input Cluster",
        "delegate_link_name": "Media Input",
        "delegate_impl_link_name": "Media Input Delegate",
        "delegate_link_url": "https://github.com/espressif/connectedhomeip/blob/d144bbb/src/app/clusters/media-input-server/media-input-delegate.h",
        "delegate_impl_link_url": "https://github.com/espressif/connectedhomeip/blob/d144bbb/examples/tv-app/tv-common/clusters/media-input/MediaInputManager.h",
    },
    {
        "display_name": "Media Playback Cluster",
        "delegate_link_name": "Media Playback",
        "delegate_impl_link_name": "Media Playback Delegate",
        "delegate_link_url": "https://github.com/espressif/connectedhomeip/blob/d144bbb/src/app/clusters/media-playback-server/media-playback-delegate.h",
        "delegate_impl_link_url": "https://github.com/espressif/connectedhomeip/blob/d144bbb/examples/tv-app/tv-common/clusters/media-playback/MediaPlaybackManager.h",
    },
    {
        "display_name": "Messages Cluster",
        "delegate_link_name": "Messages",
        "delegate_impl_link_name": "Messages Delegate",
        "delegate_link_url": "https://github.com/espressif/connectedhomeip/blob/d144bbb/src/app/clusters/messages-server/messages-delegate.h",
        "delegate_impl_link_url": "https://github.com/espressif/connectedhomeip/blob/d144bbb/examples/tv-app/tv-common/clusters/messages/MessagesManager.h",
    },
    {
        "display_name": "Microwave Oven Control Cluster",
        "delegate_link_name": "Microwave Oven Control",
        "delegate_impl_link_name": "Microwave Oven Control Delegate",
        "delegate_link_url": "https://github.com/espressif/connectedhomeip/blob/d144bbb/src/app/clusters/microwave-oven-control-server/microwave-oven-control-server.h",
        "delegate_impl_link_url": "https://github.com/espressif/connectedhomeip/blob/d144bbb/examples/microwave-oven-app/microwave-oven-common/include/microwave-oven-device.h",
    },
    {
        "display_name": "Mode Base Cluster (all derived types of clusters)",
        "delegate_link_name": "Mode Base",
        "delegate_impl_link_name": None,
        "delegate_link_url": "https://github.com/espressif/connectedhomeip/blob/d144bbb/src/app/clusters/mode-base-server/mode-base-server.h",
        "delegate_impl_link_url": None,
        "note": "It is a base cluster for ModeEVSE, ModeOven, ModeRVSRun, ModeRVSClean, ModeDishwasher,\nModeWaterHeater, ModeRefrigerator, ModeLaundryWasher and ModeMicrowaveOven.",
        "multiple_impl_link_urls": [
            ("Refrigeratore And TCC Mode", "https://github.com/espressif/connectedhomeip/blob/d144bbb/examples/all-clusters-app/all-clusters-common/include/tcc-mode.h"),
            ("Laundry Washer Mode", "https://github.com/espressif/connectedhomeip/blob/d144bbb/examples/all-clusters-app/all-clusters-common/include/laundry-washer-mode.h"),
            ("Dish Washer Mode", "https://github.com/espressif/connectedhomeip/blob/d144bbb/examples/all-clusters-app/all-clusters-common/include/dishwasher-mode.h"),
            ("Rvc Run And Rvc Clean Mode", "https://github.com/espressif/connectedhomeip/blob/d144bbb/examples/all-clusters-app/all-clusters-common/include/rvc-modes.h"),
            ("Energy Evse Mode", "https://github.com/espressif/connectedhomeip/blob/d144bbb/examples/energy-management-app/energy-management-common/energy-evse/include/energy-evse-modes.h"),
            ("Microwave Oven Mode", "https://github.com/espressif/connectedhomeip/blob/d144bbb/examples/all-clusters-app/all-clusters-common/include/microwave-oven-mode.h"),
            ("Device Energy Management Mode", "https://github.com/espressif/connectedhomeip/blob/d144bbb/examples/energy-management-app/energy-management-common/device-energy-management/include/device-energy-management-modes.h"),
            ("Water Heater Mode", "https://github.com/espressif/connectedhomeip/blob/d144bbb/examples/all-clusters-app/all-clusters-common/include/water-heater-mode.h"),
        ],
    },
    {
        "display_name": "Mode Select Cluster",
        "delegate_link_name": "Mode Select",
        "delegate_impl_link_name": "Mode Select Delegate",
        "delegate_link_url": "https://github.com/espressif/connectedhomeip/blob/d144bbb/src/app/clusters/mode-select-server/supported-modes-manager.h",
        "delegate_impl_link_url": "https://github.com/espressif/connectedhomeip/blob/d144bbb/examples/all-clusters-app/all-clusters-common/include/static-supported-modes-manager.h",
    },
    {
        "display_name": "Operational State Cluster",
        "delegate_link_name": "Operational State",
        "delegate_impl_link_name": "Operational State Delegate",
        "delegate_link_url": "https://github.com/espressif/connectedhomeip/blob/d144bbb/src/app/clusters/operational-state-server/operational-state-server.h",
        "delegate_impl_link_url": "https://github.com/espressif/connectedhomeip/blob/d144bbb/examples/all-clusters-app/all-clusters-common/include/operational-state-delegate-impl.h",
    },
    {
        "display_name": "Power Topology Cluster",
        "delegate_link_name": "Power Topology",
        "delegate_impl_link_name": "Power Topology Delegate",
        "delegate_link_url": "https://github.com/espressif/connectedhomeip/blob/d144bbb/src/app/clusters/power-topology-server/power-topology-server.h",
        "delegate_impl_link_url": "https://github.com/espressif/connectedhomeip/blob/d144bbb/examples/energy-management-app/energy-management-common/energy-reporting/include/PowerTopologyDelegate.h",
    },
    {
        "display_name": "Push AV Stream Transport Cluster",
        "delegate_link_name": "Push AV Stream Transport",
        "delegate_impl_link_name": "Push AV Stream Transport Delegate",
        "delegate_link_url": "https://github.com/espressif/connectedhomeip/blob/faf4d09/src/app/clusters/push-av-stream-transport-server/push-av-stream-transport-delegate.h",
        "delegate_impl_link_url": "https://github.com/espressif/connectedhomeip/blob/faf4d09/examples/all-clusters-app/all-clusters-common/include/push-av-stream-transport-delegate-impl.h",
    },
    {
        "display_name": "Resource Monitoring Cluster",
        "delegate_link_name": "Resource Monitoring",
        "delegate_impl_link_name": None,
        "delegate_link_url": "https://github.com/espressif/connectedhomeip/blob/d144bbb/src/app/clusters/resource-monitoring-server/resource-monitoring-server.h",
        "delegate_impl_link_url": None,
        "multiple_impl_link_urls": [
            ("HEPA Filter Monitoring Delegate", "https://github.com/espressif/connectedhomeip/blob/d144bbb/examples/all-clusters-app/all-clusters-common/include/resource-monitoring-delegates.h"),
            ("Activated Carbon Filter Monitoring Delegate", "https://github.com/espressif/connectedhomeip/blob/d144bbb/examples/all-clusters-app/all-clusters-common/include/resource-monitoring-delegates.h"),
            ("Water Tank Level Monitoring Delegate", None),
        ],
    },
    {
        "display_name": "Service Area Cluster",
        "delegate_link_name": "Service Area",
        "delegate_impl_link_name": "Service Area Delegate",
        "delegate_link_url": "https://github.com/espressif/connectedhomeip/blob/d144bbb/src/app/clusters/service-area-server/service-area-server.h",
        "delegate_impl_link_url": "https://github.com/espressif/connectedhomeip/blob/d144bbb/examples/rvc-app/rvc-common/include/rvc-service-area-delegate.h",
    },
    {
        "display_name": "Target Navigator Cluster",
        "delegate_link_name": "Target Navigator",
        "delegate_impl_link_name": "Target Navigator Delegate",
        "delegate_link_url": "https://github.com/espressif/connectedhomeip/blob/d144bbb/src/app/clusters/target-navigator-server/target-navigator-delegate.h",
        "delegate_impl_link_url": "https://github.com/espressif/connectedhomeip/blob/d144bbb/examples/tv-app/tv-common/clusters/target-navigator/TargetNavigatorManager.h",
    },
    {
        "display_name": "Thermostat Cluster",
        "delegate_link_name": "Thermostat",
        "delegate_impl_link_name": "Thermostat Delegate",
        "delegate_link_url": "https://github.com/espressif/connectedhomeip/blob/d144bbb/src/app/clusters/thermostat-server/thermostat-delegate.h",
        "delegate_impl_link_url": "https://github.com/espressif/connectedhomeip/blob/d144bbb/examples/thermostat/thermostat-common/include/thermostat-delegate-impl.h",
    },
    {
        "display_name": "Time Synchronization Cluster",
        "delegate_link_name": "Time Synchronization",
        "delegate_impl_link_name": "Time Synchronization Delegate",
        "delegate_link_url": "https://github.com/espressif/connectedhomeip/blob/d144bbb/src/app/clusters/time-synchronization-server/time-synchronization-delegate.h",
        "delegate_impl_link_url": "https://github.com/espressif/connectedhomeip/blob/d144bbb/src/app/clusters/time-synchronization-server/DefaultTimeSyncDelegate.h",
    },
    {
        "display_name": "Valve Configuration And Control Cluster",
        "delegate_link_name": "Valve Configuration And Control",
        "delegate_impl_link_name": "Valve Configuration And Control Delegate",
        "delegate_link_url": "https://github.com/espressif/connectedhomeip/blob/d144bbb/src/app/clusters/valve-configuration-and-control-server/valve-configuration-and-control-delegate.h",
        "delegate_impl_link_url": "https://github.com/espressif/connectedhomeip/blob/d144bbb/examples/all-clusters-app/linux/ValveControlDelegate.h",
    },
    {
        "display_name": "Wake On Lan Cluster",
        "delegate_link_name": "Wake On LAN",
        "delegate_impl_link_name": "Wake On LAN Delegate",
        "delegate_link_url": "https://github.com/espressif/connectedhomeip/blob/d144bbb/src/app/clusters/wake-on-lan-server/wake-on-lan-server.h",
        "delegate_impl_link_url": "https://github.com/espressif/connectedhomeip/blob/d144bbb/examples/tv-app/tv-common/clusters/wake-on-lan/WakeOnLanManager.h",
    },
    {
        "display_name": "Water Heater Management Cluster",
        "delegate_link_name": "Water Heater Management",
        "delegate_impl_link_name": "Water Heater Management Delegate",
        "delegate_link_url": "https://github.com/espressif/connectedhomeip/blob/d144bbb/src/app/clusters/water-heater-management-server/water-heater-management-server.h",
        "delegate_impl_link_url": "https://github.com/espressif/connectedhomeip/blob/d144bbb/examples/all-clusters-app/all-clusters-common/include/WhmDelegate.h",
    },
    {
        "display_name": "WebRTC Transport Provider Cluster",
        "delegate_link_name": "WebRTC Transport Provider",
        "delegate_impl_link_name": "WebRTC Transport Provider Delegate",
        "delegate_link_url": "https://github.com/espressif/connectedhomeip/blob/d144bbb/src/app/clusters/webrtc-transport-provider-server/webrtc-transport-provider-server.h",
        "delegate_impl_link_url": "https://github.com/espressif/connectedhomeip/blob/d144bbb/examples/camera-app/linux/include/clusters/webrtc_provider/webrtc-provider-manager.h",
    },
    {
        "display_name": "Window Covering Cluster",
        "delegate_link_name": "Window Covering",
        "delegate_impl_link_name": "Window Covering Delegate",
        "delegate_link_url": "https://github.com/espressif/connectedhomeip/blob/d144bbb/src/app/clusters/window-covering-server/window-covering-delegate.h",
        "delegate_impl_link_url": "https://github.com/espressif/connectedhomeip/blob/d144bbb/examples/chef/common/clusters/window-covering/chef-window-covering.h",
    },
    {
        "display_name": "Chime Cluster",
        "delegate_link_name": "Chime",
        "delegate_impl_link_name": "Chime Delegate",
        "delegate_link_url": "https://github.com/espressif/connectedhomeip/blob/faf4d09/src/app/clusters/chime-server/chime-server.h",
        "delegate_impl_link_url": "https://github.com/espressif/connectedhomeip/blob/faf4d09/examples/all-clusters-app/all-clusters-common/include/chime-instance.h",
    },
]
